version: '3.1'

services:
  db:
    container_name: terpal-sql-example
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 35433:5432
    volumes:
      - ./src/main/sql:/docker-entrypoint-initdb.d/:ro